apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-db-secret
    labels:
        {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.env.DB_HOST | b64enc | quote }}
  DB_PORT: {{ .Values.env.DB_PORT | toString | b64enc | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | b64enc | quote }}
  DB_USER: {{ .Values.env.DB_USER | b64enc | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc | quote }}
