// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBlogStmt, err = db.PrepareContext(ctx, createBlog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlog: %w", err)
	}
	if q.createOrderStmt, err = db.PrepareContext(ctx, createOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrder: %w", err)
	}
	if q.createOrderItemStmt, err = db.PrepareContext(ctx, createOrderItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrderItem: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createTenantStmt, err = db.PrepareContext(ctx, createTenant); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTenant: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getTenantBySlugStmt, err = db.PrepareContext(ctx, getTenantBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetTenantBySlug: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.listBlogsStmt, err = db.PrepareContext(ctx, listBlogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListBlogs: %w", err)
	}
	if q.listProductsStmt, err = db.PrepareContext(ctx, listProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListProducts: %w", err)
	}
	if q.listTenantsStmt, err = db.PrepareContext(ctx, listTenants); err != nil {
		return nil, fmt.Errorf("error preparing query ListTenants: %w", err)
	}
	if q.updateProductStockStmt, err = db.PrepareContext(ctx, updateProductStock); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductStock: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBlogStmt != nil {
		if cerr := q.createBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlogStmt: %w", cerr)
		}
	}
	if q.createOrderStmt != nil {
		if cerr := q.createOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderStmt: %w", cerr)
		}
	}
	if q.createOrderItemStmt != nil {
		if cerr := q.createOrderItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderItemStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createTenantStmt != nil {
		if cerr := q.createTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTenantStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getTenantBySlugStmt != nil {
		if cerr := q.getTenantBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTenantBySlugStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.listBlogsStmt != nil {
		if cerr := q.listBlogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBlogsStmt: %w", cerr)
		}
	}
	if q.listProductsStmt != nil {
		if cerr := q.listProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsStmt: %w", cerr)
		}
	}
	if q.listTenantsStmt != nil {
		if cerr := q.listTenantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTenantsStmt: %w", cerr)
		}
	}
	if q.updateProductStockStmt != nil {
		if cerr := q.updateProductStockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStockStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createBlogStmt         *sql.Stmt
	createOrderStmt        *sql.Stmt
	createOrderItemStmt    *sql.Stmt
	createProductStmt      *sql.Stmt
	createTenantStmt       *sql.Stmt
	createUserStmt         *sql.Stmt
	getTenantBySlugStmt    *sql.Stmt
	getUserByEmailStmt     *sql.Stmt
	listBlogsStmt          *sql.Stmt
	listProductsStmt       *sql.Stmt
	listTenantsStmt        *sql.Stmt
	updateProductStockStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createBlogStmt:         q.createBlogStmt,
		createOrderStmt:        q.createOrderStmt,
		createOrderItemStmt:    q.createOrderItemStmt,
		createProductStmt:      q.createProductStmt,
		createTenantStmt:       q.createTenantStmt,
		createUserStmt:         q.createUserStmt,
		getTenantBySlugStmt:    q.getTenantBySlugStmt,
		getUserByEmailStmt:     q.getUserByEmailStmt,
		listBlogsStmt:          q.listBlogsStmt,
		listProductsStmt:       q.listProductsStmt,
		listTenantsStmt:        q.listTenantsStmt,
		updateProductStockStmt: q.updateProductStockStmt,
	}
}
