// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addTenantOwnerStmt, err = db.PrepareContext(ctx, addTenantOwner); err != nil {
		return nil, fmt.Errorf("error preparing query AddTenantOwner: %w", err)
	}
	if q.createBlogStmt, err = db.PrepareContext(ctx, createBlog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlog: %w", err)
	}
	if q.createOrderStmt, err = db.PrepareContext(ctx, createOrder); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrder: %w", err)
	}
	if q.createOrderItemStmt, err = db.PrepareContext(ctx, createOrderItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrderItem: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createReviewStmt, err = db.PrepareContext(ctx, createReview); err != nil {
		return nil, fmt.Errorf("error preparing query CreateReview: %w", err)
	}
	if q.createTenantStmt, err = db.PrepareContext(ctx, createTenant); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTenant: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.deleteBlogStmt, err = db.PrepareContext(ctx, deleteBlog); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlog: %w", err)
	}
	if q.deleteProductStmt, err = db.PrepareContext(ctx, deleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProduct: %w", err)
	}
	if q.deleteTenantStmt, err = db.PrepareContext(ctx, deleteTenant); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteTenant: %w", err)
	}
	if q.getAverageRatingStmt, err = db.PrepareContext(ctx, getAverageRating); err != nil {
		return nil, fmt.Errorf("error preparing query GetAverageRating: %w", err)
	}
	if q.getOrderItemsStmt, err = db.PrepareContext(ctx, getOrderItems); err != nil {
		return nil, fmt.Errorf("error preparing query GetOrderItems: %w", err)
	}
	if q.getProductStmt, err = db.PrepareContext(ctx, getProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetProduct: %w", err)
	}
	if q.getRevenueByDayStmt, err = db.PrepareContext(ctx, getRevenueByDay); err != nil {
		return nil, fmt.Errorf("error preparing query GetRevenueByDay: %w", err)
	}
	if q.getTenantBySlugStmt, err = db.PrepareContext(ctx, getTenantBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetTenantBySlug: %w", err)
	}
	if q.getTopSellingProductsStmt, err = db.PrepareContext(ctx, getTopSellingProducts); err != nil {
		return nil, fmt.Errorf("error preparing query GetTopSellingProducts: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserDiscountStmt, err = db.PrepareContext(ctx, getUserDiscount); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserDiscount: %w", err)
	}
	if q.isTenantOwnerStmt, err = db.PrepareContext(ctx, isTenantOwner); err != nil {
		return nil, fmt.Errorf("error preparing query IsTenantOwner: %w", err)
	}
	if q.listBlogsStmt, err = db.PrepareContext(ctx, listBlogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListBlogs: %w", err)
	}
	if q.listCategoriesStmt, err = db.PrepareContext(ctx, listCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategories: %w", err)
	}
	if q.listOrdersByTenantStmt, err = db.PrepareContext(ctx, listOrdersByTenant); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrdersByTenant: %w", err)
	}
	if q.listOrdersByUserStmt, err = db.PrepareContext(ctx, listOrdersByUser); err != nil {
		return nil, fmt.Errorf("error preparing query ListOrdersByUser: %w", err)
	}
	if q.listProductsStmt, err = db.PrepareContext(ctx, listProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListProducts: %w", err)
	}
	if q.listReviewsByProductStmt, err = db.PrepareContext(ctx, listReviewsByProduct); err != nil {
		return nil, fmt.Errorf("error preparing query ListReviewsByProduct: %w", err)
	}
	if q.listTenantCategoriesStmt, err = db.PrepareContext(ctx, listTenantCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListTenantCategories: %w", err)
	}
	if q.listTenantOwnersStmt, err = db.PrepareContext(ctx, listTenantOwners); err != nil {
		return nil, fmt.Errorf("error preparing query ListTenantOwners: %w", err)
	}
	if q.listTenantsStmt, err = db.PrepareContext(ctx, listTenants); err != nil {
		return nil, fmt.Errorf("error preparing query ListTenants: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.removeTenantOwnerStmt, err = db.PrepareContext(ctx, removeTenantOwner); err != nil {
		return nil, fmt.Errorf("error preparing query RemoveTenantOwner: %w", err)
	}
	if q.setTenantOwnerStmt, err = db.PrepareContext(ctx, setTenantOwner); err != nil {
		return nil, fmt.Errorf("error preparing query SetTenantOwner: %w", err)
	}
	if q.updateBlogStmt, err = db.PrepareContext(ctx, updateBlog); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBlog: %w", err)
	}
	if q.updateOrderStatusStmt, err = db.PrepareContext(ctx, updateOrderStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOrderStatus: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	if q.updateProductStockStmt, err = db.PrepareContext(ctx, updateProductStock); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductStock: %w", err)
	}
	if q.updateTenantStmt, err = db.PrepareContext(ctx, updateTenant); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTenant: %w", err)
	}
	if q.updateTenantAppearanceStmt, err = db.PrepareContext(ctx, updateTenantAppearance); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTenantAppearance: %w", err)
	}
	if q.updateTenantIconStmt, err = db.PrepareContext(ctx, updateTenantIcon); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTenantIcon: %w", err)
	}
	if q.updateUserLoyaltyTierStmt, err = db.PrepareContext(ctx, updateUserLoyaltyTier); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserLoyaltyTier: %w", err)
	}
	if q.updateUserRoleStmt, err = db.PrepareContext(ctx, updateUserRole); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserRole: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addTenantOwnerStmt != nil {
		if cerr := q.addTenantOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addTenantOwnerStmt: %w", cerr)
		}
	}
	if q.createBlogStmt != nil {
		if cerr := q.createBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlogStmt: %w", cerr)
		}
	}
	if q.createOrderStmt != nil {
		if cerr := q.createOrderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderStmt: %w", cerr)
		}
	}
	if q.createOrderItemStmt != nil {
		if cerr := q.createOrderItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrderItemStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createReviewStmt != nil {
		if cerr := q.createReviewStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createReviewStmt: %w", cerr)
		}
	}
	if q.createTenantStmt != nil {
		if cerr := q.createTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTenantStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.deleteBlogStmt != nil {
		if cerr := q.deleteBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlogStmt: %w", cerr)
		}
	}
	if q.deleteProductStmt != nil {
		if cerr := q.deleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductStmt: %w", cerr)
		}
	}
	if q.deleteTenantStmt != nil {
		if cerr := q.deleteTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteTenantStmt: %w", cerr)
		}
	}
	if q.getAverageRatingStmt != nil {
		if cerr := q.getAverageRatingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAverageRatingStmt: %w", cerr)
		}
	}
	if q.getOrderItemsStmt != nil {
		if cerr := q.getOrderItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOrderItemsStmt: %w", cerr)
		}
	}
	if q.getProductStmt != nil {
		if cerr := q.getProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductStmt: %w", cerr)
		}
	}
	if q.getRevenueByDayStmt != nil {
		if cerr := q.getRevenueByDayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRevenueByDayStmt: %w", cerr)
		}
	}
	if q.getTenantBySlugStmt != nil {
		if cerr := q.getTenantBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTenantBySlugStmt: %w", cerr)
		}
	}
	if q.getTopSellingProductsStmt != nil {
		if cerr := q.getTopSellingProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTopSellingProductsStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserDiscountStmt != nil {
		if cerr := q.getUserDiscountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserDiscountStmt: %w", cerr)
		}
	}
	if q.isTenantOwnerStmt != nil {
		if cerr := q.isTenantOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing isTenantOwnerStmt: %w", cerr)
		}
	}
	if q.listBlogsStmt != nil {
		if cerr := q.listBlogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBlogsStmt: %w", cerr)
		}
	}
	if q.listCategoriesStmt != nil {
		if cerr := q.listCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoriesStmt: %w", cerr)
		}
	}
	if q.listOrdersByTenantStmt != nil {
		if cerr := q.listOrdersByTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrdersByTenantStmt: %w", cerr)
		}
	}
	if q.listOrdersByUserStmt != nil {
		if cerr := q.listOrdersByUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOrdersByUserStmt: %w", cerr)
		}
	}
	if q.listProductsStmt != nil {
		if cerr := q.listProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsStmt: %w", cerr)
		}
	}
	if q.listReviewsByProductStmt != nil {
		if cerr := q.listReviewsByProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listReviewsByProductStmt: %w", cerr)
		}
	}
	if q.listTenantCategoriesStmt != nil {
		if cerr := q.listTenantCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTenantCategoriesStmt: %w", cerr)
		}
	}
	if q.listTenantOwnersStmt != nil {
		if cerr := q.listTenantOwnersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTenantOwnersStmt: %w", cerr)
		}
	}
	if q.listTenantsStmt != nil {
		if cerr := q.listTenantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTenantsStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.removeTenantOwnerStmt != nil {
		if cerr := q.removeTenantOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing removeTenantOwnerStmt: %w", cerr)
		}
	}
	if q.setTenantOwnerStmt != nil {
		if cerr := q.setTenantOwnerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setTenantOwnerStmt: %w", cerr)
		}
	}
	if q.updateBlogStmt != nil {
		if cerr := q.updateBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBlogStmt: %w", cerr)
		}
	}
	if q.updateOrderStatusStmt != nil {
		if cerr := q.updateOrderStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOrderStatusStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	if q.updateProductStockStmt != nil {
		if cerr := q.updateProductStockStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStockStmt: %w", cerr)
		}
	}
	if q.updateTenantStmt != nil {
		if cerr := q.updateTenantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTenantStmt: %w", cerr)
		}
	}
	if q.updateTenantAppearanceStmt != nil {
		if cerr := q.updateTenantAppearanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTenantAppearanceStmt: %w", cerr)
		}
	}
	if q.updateTenantIconStmt != nil {
		if cerr := q.updateTenantIconStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTenantIconStmt: %w", cerr)
		}
	}
	if q.updateUserLoyaltyTierStmt != nil {
		if cerr := q.updateUserLoyaltyTierStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserLoyaltyTierStmt: %w", cerr)
		}
	}
	if q.updateUserRoleStmt != nil {
		if cerr := q.updateUserRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserRoleStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	addTenantOwnerStmt         *sql.Stmt
	createBlogStmt             *sql.Stmt
	createOrderStmt            *sql.Stmt
	createOrderItemStmt        *sql.Stmt
	createProductStmt          *sql.Stmt
	createReviewStmt           *sql.Stmt
	createTenantStmt           *sql.Stmt
	createUserStmt             *sql.Stmt
	deleteBlogStmt             *sql.Stmt
	deleteProductStmt          *sql.Stmt
	deleteTenantStmt           *sql.Stmt
	getAverageRatingStmt       *sql.Stmt
	getOrderItemsStmt          *sql.Stmt
	getProductStmt             *sql.Stmt
	getRevenueByDayStmt        *sql.Stmt
	getTenantBySlugStmt        *sql.Stmt
	getTopSellingProductsStmt  *sql.Stmt
	getUserByEmailStmt         *sql.Stmt
	getUserByIDStmt            *sql.Stmt
	getUserDiscountStmt        *sql.Stmt
	isTenantOwnerStmt          *sql.Stmt
	listBlogsStmt              *sql.Stmt
	listCategoriesStmt         *sql.Stmt
	listOrdersByTenantStmt     *sql.Stmt
	listOrdersByUserStmt       *sql.Stmt
	listProductsStmt           *sql.Stmt
	listReviewsByProductStmt   *sql.Stmt
	listTenantCategoriesStmt   *sql.Stmt
	listTenantOwnersStmt       *sql.Stmt
	listTenantsStmt            *sql.Stmt
	listUsersStmt              *sql.Stmt
	removeTenantOwnerStmt      *sql.Stmt
	setTenantOwnerStmt         *sql.Stmt
	updateBlogStmt             *sql.Stmt
	updateOrderStatusStmt      *sql.Stmt
	updateProductStmt          *sql.Stmt
	updateProductStockStmt     *sql.Stmt
	updateTenantStmt           *sql.Stmt
	updateTenantAppearanceStmt *sql.Stmt
	updateTenantIconStmt       *sql.Stmt
	updateUserLoyaltyTierStmt  *sql.Stmt
	updateUserRoleStmt         *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		addTenantOwnerStmt:         q.addTenantOwnerStmt,
		createBlogStmt:             q.createBlogStmt,
		createOrderStmt:            q.createOrderStmt,
		createOrderItemStmt:        q.createOrderItemStmt,
		createProductStmt:          q.createProductStmt,
		createReviewStmt:           q.createReviewStmt,
		createTenantStmt:           q.createTenantStmt,
		createUserStmt:             q.createUserStmt,
		deleteBlogStmt:             q.deleteBlogStmt,
		deleteProductStmt:          q.deleteProductStmt,
		deleteTenantStmt:           q.deleteTenantStmt,
		getAverageRatingStmt:       q.getAverageRatingStmt,
		getOrderItemsStmt:          q.getOrderItemsStmt,
		getProductStmt:             q.getProductStmt,
		getRevenueByDayStmt:        q.getRevenueByDayStmt,
		getTenantBySlugStmt:        q.getTenantBySlugStmt,
		getTopSellingProductsStmt:  q.getTopSellingProductsStmt,
		getUserByEmailStmt:         q.getUserByEmailStmt,
		getUserByIDStmt:            q.getUserByIDStmt,
		getUserDiscountStmt:        q.getUserDiscountStmt,
		isTenantOwnerStmt:          q.isTenantOwnerStmt,
		listBlogsStmt:              q.listBlogsStmt,
		listCategoriesStmt:         q.listCategoriesStmt,
		listOrdersByTenantStmt:     q.listOrdersByTenantStmt,
		listOrdersByUserStmt:       q.listOrdersByUserStmt,
		listProductsStmt:           q.listProductsStmt,
		listReviewsByProductStmt:   q.listReviewsByProductStmt,
		listTenantCategoriesStmt:   q.listTenantCategoriesStmt,
		listTenantOwnersStmt:       q.listTenantOwnersStmt,
		listTenantsStmt:            q.listTenantsStmt,
		listUsersStmt:              q.listUsersStmt,
		removeTenantOwnerStmt:      q.removeTenantOwnerStmt,
		setTenantOwnerStmt:         q.setTenantOwnerStmt,
		updateBlogStmt:             q.updateBlogStmt,
		updateOrderStatusStmt:      q.updateOrderStatusStmt,
		updateProductStmt:          q.updateProductStmt,
		updateProductStockStmt:     q.updateProductStockStmt,
		updateTenantStmt:           q.updateTenantStmt,
		updateTenantAppearanceStmt: q.updateTenantAppearanceStmt,
		updateTenantIconStmt:       q.updateTenantIconStmt,
		updateUserLoyaltyTierStmt:  q.updateUserLoyaltyTierStmt,
		updateUserRoleStmt:         q.updateUserRoleStmt,
	}
}
