// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Blog struct {
	ID          uuid.UUID    `json:"id"`
	TenantID    uuid.UUID    `json:"tenant_id"`
	Title       string       `json:"title"`
	ContentMd   string       `json:"content_md"`
	PublishedAt sql.NullTime `json:"published_at"`
}

type Order struct {
	ID          uuid.UUID    `json:"id"`
	TenantID    uuid.UUID    `json:"tenant_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Status      string       `json:"status"`
	TotalAmount string       `json:"total_amount"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type OrderItem struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    int32     `json:"quantity"`
	PriceAtTime string    `json:"price_at_time"`
}

type Product struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    sql.NullString `json:"image_url"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type ProductReview struct {
	ID        uuid.UUID      `json:"id"`
	ProductID uuid.UUID      `json:"product_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
}

type Tenant struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	IconUrl     sql.NullString `json:"icon_url"`
	CoverUrl    sql.NullString `json:"cover_url"`
	Description sql.NullString `json:"description"`
	OwnerID     uuid.NullUUID  `json:"owner_id"`
}

type TenantOwner struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	TenantID     uuid.NullUUID `json:"tenant_id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Role         string        `json:"role"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}
