// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (tenant_id, title, content_md)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, title, content_md, published_at
`

type CreateBlogParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog, arg.TenantID, arg.Title, arg.ContentMd)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ContentMd,
		&i.PublishedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (tenant_id, user_id, status, total_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, status, total_amount, created_at
`

type CreateOrderParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	TotalAmount string    `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder,
		arg.TenantID,
		arg.UserID,
		arg.Status,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_at_time)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_at_time
`

type CreateOrderItemParams struct {
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    int32     `json:"quantity"`
	PriceAtTime string    `json:"price_at_time"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.queryRow(ctx, q.createOrderItemStmt, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtTime,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtTime,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (tenant_id, name, description, price, stock, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at
`

type CreateProductParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.queryRow(ctx, q.createTenantStmt, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, role, created_at
`

type CreateUserParams struct {
	TenantID     uuid.NullUUID `json:"tenant_id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Role         string        `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs WHERE id = $1 AND tenant_id = $2
`

type DeleteBlogParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteBlog(ctx context.Context, arg DeleteBlogParams) error {
	_, err := q.exec(ctx, q.deleteBlogStmt, deleteBlog, arg.ID, arg.TenantID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1 AND tenant_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, arg.ID, arg.TenantID)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteTenantStmt, deleteTenant, id)
	return err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price_at_time, p.name as product_name 
FROM order_items oi
JOIN products p ON oi.product_id = p.id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    int32     `json:"quantity"`
	PriceAtTime string    `json:"price_at_time"`
	ProductName string    `json:"product_name"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.query(ctx, q.getOrderItemsStmt, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceAtTime,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, created_at, icon_url, cover_url, description, owner_id FROM tenants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.queryRow(ctx, q.getTenantBySlugStmt, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role, created_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, tenant_id, title, content_md, published_at FROM blogs WHERE tenant_id = $1 ORDER BY published_at DESC
`

func (q *Queries) ListBlogs(ctx context.Context, tenantID uuid.UUID) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blog
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.ContentMd,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByTenant = `-- name: ListOrdersByTenant :many
SELECT id, tenant_id, user_id, status, total_amount, created_at FROM orders WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByTenant(ctx context.Context, tenantID uuid.UUID) ([]Order, error) {
	rows, err := q.query(ctx, q.listOrdersByTenantStmt, listOrdersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, tenant_id, user_id, status, total_amount, created_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.query(ctx, q.listOrdersByUserStmt, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, name, description, price, stock, image_url, created_at FROM products WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context, tenantID uuid.UUID) ([]Product, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, created_at, icon_url, cover_url, description, owner_id FROM tenants ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.query(ctx, q.listTenantsStmt, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.IconUrl,
			&i.CoverUrl,
			&i.Description,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, role, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantOwner = `-- name: SetTenantOwner :one
UPDATE tenants SET owner_id = $2 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id
`

type SetTenantOwnerParams struct {
	ID      uuid.UUID     `json:"id"`
	OwnerID uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) SetTenantOwner(ctx context.Context, arg SetTenantOwnerParams) (Tenant, error) {
	row := q.queryRow(ctx, q.setTenantOwnerStmt, setTenantOwner, arg.ID, arg.OwnerID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
	)
	return i, err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
SET title = $2, content_md = $3
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, title, content_md, published_at
`

type UpdateBlogParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.updateBlogStmt, updateBlog,
		arg.ID,
		arg.Title,
		arg.ContentMd,
		arg.TenantID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ContentMd,
		&i.PublishedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2 WHERE id = $1 AND tenant_id = $3 RETURNING id, tenant_id, user_id, status, total_amount, created_at
`

type UpdateOrderStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.queryRow(ctx, q.updateOrderStatusStmt, updateOrderStatus, arg.ID, arg.Status, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products 
SET name = $2, description = $3, price = $4, stock = $5, image_url = $6
WHERE id = $1 AND tenant_id = $7
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    sql.NullString `json:"image_url"`
	TenantID    uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStmt, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.TenantID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products SET stock = stock - $2
WHERE id = $1 AND tenant_id = $3 AND stock >= $2
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at
`

type UpdateProductStockParams struct {
	ID       uuid.UUID `json:"id"`
	Stock    int32     `json:"stock"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStockStmt, updateProductStock, arg.ID, arg.Stock, arg.TenantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, slug = $3 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id
`

type UpdateTenantParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.queryRow(ctx, q.updateTenantStmt, updateTenant, arg.ID, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
	)
	return i, err
}

const updateTenantAppearance = `-- name: UpdateTenantAppearance :one
UPDATE tenants SET cover_url = $2, description = $3 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id
`

type UpdateTenantAppearanceParams struct {
	ID          uuid.UUID      `json:"id"`
	CoverUrl    sql.NullString `json:"cover_url"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateTenantAppearance(ctx context.Context, arg UpdateTenantAppearanceParams) (Tenant, error) {
	row := q.queryRow(ctx, q.updateTenantAppearanceStmt, updateTenantAppearance, arg.ID, arg.CoverUrl, arg.Description)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
	)
	return i, err
}

const updateTenantIcon = `-- name: UpdateTenantIcon :one
UPDATE tenants SET icon_url = $2 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id
`

type UpdateTenantIconParams struct {
	ID      uuid.UUID      `json:"id"`
	IconUrl sql.NullString `json:"icon_url"`
}

func (q *Queries) UpdateTenantIcon(ctx context.Context, arg UpdateTenantIconParams) (Tenant, error) {
	row := q.queryRow(ctx, q.updateTenantIconStmt, updateTenantIcon, arg.ID, arg.IconUrl)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, tenant_id, email, password_hash, role, created_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserRoleStmt, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
