// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (tenant_id, title, content_md)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, title, content_md, published_at
`

type CreateBlogParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog, arg.TenantID, arg.Title, arg.ContentMd)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ContentMd,
		&i.PublishedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (tenant_id, user_id, status, total_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, status, total_amount, created_at
`

type CreateOrderParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	TotalAmount string    `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder,
		arg.TenantID,
		arg.UserID,
		arg.Status,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_at_time)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_at_time
`

type CreateOrderItemParams struct {
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    int32     `json:"quantity"`
	PriceAtTime string    `json:"price_at_time"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.queryRow(ctx, q.createOrderItemStmt, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtTime,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtTime,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (tenant_id, name, description, price, stock, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at
`

type CreateProductParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    sql.NullString `json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.queryRow(ctx, q.createTenantStmt, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, role, created_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, created_at FROM tenants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.queryRow(ctx, q.getTenantBySlugStmt, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, tenant_id, title, content_md, published_at FROM blogs WHERE tenant_id = $1 ORDER BY published_at DESC
`

func (q *Queries) ListBlogs(ctx context.Context, tenantID uuid.UUID) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blog
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.ContentMd,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, name, description, price, stock, image_url, created_at FROM products WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context, tenantID uuid.UUID) ([]Product, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, created_at FROM tenants ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.query(ctx, q.listTenantsStmt, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products SET stock = stock - $2
WHERE id = $1 AND tenant_id = $3 AND stock >= $2
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at
`

type UpdateProductStockParams struct {
	ID       uuid.UUID `json:"id"`
	Stock    int32     `json:"stock"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStockStmt, updateProductStock, arg.ID, arg.Stock, arg.TenantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
	)
	return i, err
}
