// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBlog(ctx context.Context, arg DeleteBlogParams) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListBlogs(ctx context.Context, tenantID uuid.UUID) ([]Blog, error)
	ListOrdersByTenant(ctx context.Context, tenantID uuid.UUID) ([]Order, error)
	ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error)
	ListProducts(ctx context.Context, tenantID uuid.UUID) ([]Product, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	SetTenantOwner(ctx context.Context, arg SetTenantOwnerParams) (Tenant, error)
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateTenantAppearance(ctx context.Context, arg UpdateTenantAppearanceParams) (Tenant, error)
	UpdateTenantIcon(ctx context.Context, arg UpdateTenantIconParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
