// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addTenantOwner = `-- name: AddTenantOwner :exec
INSERT INTO tenant_owners (tenant_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTenantOwnerParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) AddTenantOwner(ctx context.Context, arg AddTenantOwnerParams) error {
	_, err := q.exec(ctx, q.addTenantOwnerStmt, addTenantOwner, arg.TenantID, arg.UserID)
	return err
}

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (tenant_id, title, content_md)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, title, content_md, published_at
`

type CreateBlogParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog, arg.TenantID, arg.Title, arg.ContentMd)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ContentMd,
		&i.PublishedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (tenant_id, user_id, status, total_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, status, total_amount, created_at
`

type CreateOrderParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	UserID      uuid.UUID `json:"user_id"`
	Status      string    `json:"status"`
	TotalAmount string    `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.queryRow(ctx, q.createOrderStmt, createOrder,
		arg.TenantID,
		arg.UserID,
		arg.Status,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_at_time)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_at_time
`

type CreateOrderItemParams struct {
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    int32     `json:"quantity"`
	PriceAtTime string    `json:"price_at_time"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.queryRow(ctx, q.createOrderItemStmt, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtTime,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtTime,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (tenant_id, name, description, price, stock, image_url, category)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at, category
`

type CreateProductParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    sql.NullString `json:"image_url"`
	Category    sql.NullString `json:"category"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.Category,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO product_reviews (product_id, user_id, rating, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, user_id, rating, comment, created_at
`

type CreateReviewParams struct {
	ProductID uuid.UUID      `json:"product_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (ProductReview, error) {
	row := q.queryRow(ctx, q.createReviewStmt, createReview,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i ProductReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id, category
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.queryRow(ctx, q.createTenantStmt, createTenant, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
		&i.Category,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city
`

type CreateUserParams struct {
	TenantID     uuid.NullUUID `json:"tenant_id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Role         string        `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.LoyaltyTier,
		&i.FullName,
		&i.Street,
		&i.ZipCode,
		&i.City,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs WHERE id = $1 AND tenant_id = $2
`

type DeleteBlogParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteBlog(ctx context.Context, arg DeleteBlogParams) error {
	_, err := q.exec(ctx, q.deleteBlogStmt, deleteBlog, arg.ID, arg.TenantID)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1 AND tenant_id = $2
`

type DeleteProductParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.exec(ctx, q.deleteProductStmt, deleteProduct, arg.ID, arg.TenantID)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteTenantStmt, deleteTenant, id)
	return err
}

const getAverageRating = `-- name: GetAverageRating :one
SELECT AVG(rating)::float as avg_rating, COUNT(*)::int as review_count
FROM product_reviews
WHERE product_id = $1
`

type GetAverageRatingRow struct {
	AvgRating   float64 `json:"avg_rating"`
	ReviewCount int32   `json:"review_count"`
}

func (q *Queries) GetAverageRating(ctx context.Context, productID uuid.UUID) (GetAverageRatingRow, error) {
	row := q.queryRow(ctx, q.getAverageRatingStmt, getAverageRating, productID)
	var i GetAverageRatingRow
	err := row.Scan(&i.AvgRating, &i.ReviewCount)
	return i, err
}

const getBlog = `-- name: GetBlog :one
SELECT id, tenant_id, title, content_md, published_at FROM blogs WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBlog(ctx context.Context, id uuid.UUID) (Blog, error) {
	row := q.queryRow(ctx, q.getBlogStmt, getBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ContentMd,
		&i.PublishedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price_at_time, p.name as product_name 
FROM order_items oi
JOIN products p ON oi.product_id = p.id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID          uuid.UUID `json:"id"`
	OrderID     uuid.UUID `json:"order_id"`
	ProductID   uuid.UUID `json:"product_id"`
	Quantity    int32     `json:"quantity"`
	PriceAtTime string    `json:"price_at_time"`
	ProductName string    `json:"product_name"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error) {
	rows, err := q.query(ctx, q.getOrderItemsStmt, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.PriceAtTime,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, tenant_id, name, description, price, stock, image_url, created_at, category FROM products WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.queryRow(ctx, q.getProductStmt, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const getRevenueByDay = `-- name: GetRevenueByDay :many
SELECT date_trunc('day', created_at)::date as day, SUM(total_amount::numeric) as revenue
FROM orders
WHERE tenant_id = $1 AND status = 'completed'
GROUP BY day
ORDER BY day DESC
LIMIT 30
`

type GetRevenueByDayRow struct {
	Day     time.Time `json:"day"`
	Revenue int64     `json:"revenue"`
}

func (q *Queries) GetRevenueByDay(ctx context.Context, tenantID uuid.UUID) ([]GetRevenueByDayRow, error) {
	rows, err := q.query(ctx, q.getRevenueByDayStmt, getRevenueByDay, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByDayRow
	for rows.Next() {
		var i GetRevenueByDayRow
		if err := rows.Scan(&i.Day, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, created_at, icon_url, cover_url, description, owner_id, category FROM tenants WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.queryRow(ctx, q.getTenantBySlugStmt, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
		&i.Category,
	)
	return i, err
}

const getTopSellingProducts = `-- name: GetTopSellingProducts :many
SELECT p.id, p.name, SUM(oi.quantity) as total_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.id
JOIN orders o ON oi.order_id = o.id
WHERE o.tenant_id = $1 AND o.status = 'completed'
GROUP BY p.id, p.name
ORDER BY total_sold DESC
LIMIT 5
`

type GetTopSellingProductsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	TotalSold int64     `json:"total_sold"`
}

func (q *Queries) GetTopSellingProducts(ctx context.Context, tenantID uuid.UUID) ([]GetTopSellingProductsRow, error) {
	rows, err := q.query(ctx, q.getTopSellingProductsStmt, getTopSellingProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSellingProductsRow
	for rows.Next() {
		var i GetTopSellingProductsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TotalSold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.LoyaltyTier,
		&i.FullName,
		&i.Street,
		&i.ZipCode,
		&i.City,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.LoyaltyTier,
		&i.FullName,
		&i.Street,
		&i.ZipCode,
		&i.City,
	)
	return i, err
}

const getUserDiscount = `-- name: GetUserDiscount :one
SELECT ld.discount_percent 
FROM loyalty_discounts ld
JOIN users u ON u.loyalty_tier = ld.tier_name
WHERE u.id = $1
`

func (q *Queries) GetUserDiscount(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.queryRow(ctx, q.getUserDiscountStmt, getUserDiscount, id)
	var discount_percent string
	err := row.Scan(&discount_percent)
	return discount_percent, err
}

const isTenantOwner = `-- name: IsTenantOwner :one
SELECT EXISTS (
    SELECT 1 FROM tenant_owners 
    WHERE tenant_id = $1 AND user_id = $2
)
`

type IsTenantOwnerParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) IsTenantOwner(ctx context.Context, arg IsTenantOwnerParams) (bool, error) {
	row := q.queryRow(ctx, q.isTenantOwnerStmt, isTenantOwner, arg.TenantID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, tenant_id, title, content_md, published_at FROM blogs WHERE tenant_id = $1 ORDER BY published_at DESC
`

func (q *Queries) ListBlogs(ctx context.Context, tenantID uuid.UUID) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blog
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.ContentMd,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT DISTINCT category FROM products WHERE tenant_id = $1
`

func (q *Queries) ListCategories(ctx context.Context, tenantID uuid.UUID) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.listCategoriesStmt, listCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByTenant = `-- name: ListOrdersByTenant :many
SELECT id, tenant_id, user_id, status, total_amount, created_at FROM orders WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByTenant(ctx context.Context, tenantID uuid.UUID) ([]Order, error) {
	rows, err := q.query(ctx, q.listOrdersByTenantStmt, listOrdersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, tenant_id, user_id, status, total_amount, created_at FROM orders WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]Order, error) {
	rows, err := q.query(ctx, q.listOrdersByUserStmt, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Status,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, name, description, price, stock, image_url, created_at, category FROM products 
WHERE tenant_id = $1 
AND (name ILIKE '%' || $2 || '%' OR COALESCE(category, '') ILIKE '%' || $2 || '%')
AND (COALESCE(category, '') = $3 OR $3 = '')
ORDER BY created_at DESC
`

type ListProductsParams struct {
	TenantID uuid.UUID      `json:"tenant_id"`
	Column2  sql.NullString `json:"column_2"`
	Category sql.NullString `json:"category"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.query(ctx, q.listProductsStmt, listProducts, arg.TenantID, arg.Column2, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProduct = `-- name: ListReviewsByProduct :many
SELECT pr.id, pr.product_id, pr.user_id, pr.rating, pr.comment, pr.created_at, u.email as user_email
FROM product_reviews pr
JOIN users u ON pr.user_id = u.id
WHERE pr.product_id = $1
ORDER BY pr.created_at DESC
`

type ListReviewsByProductRow struct {
	ID        uuid.UUID      `json:"id"`
	ProductID uuid.UUID      `json:"product_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Rating    int32          `json:"rating"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
	UserEmail string         `json:"user_email"`
}

func (q *Queries) ListReviewsByProduct(ctx context.Context, productID uuid.UUID) ([]ListReviewsByProductRow, error) {
	rows, err := q.query(ctx, q.listReviewsByProductStmt, listReviewsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByProductRow
	for rows.Next() {
		var i ListReviewsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantCategories = `-- name: ListTenantCategories :many
SELECT DISTINCT category FROM tenants
`

func (q *Queries) ListTenantCategories(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.query(ctx, q.listTenantCategoriesStmt, listTenantCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantOwners = `-- name: ListTenantOwners :many
SELECT u.id, u.email, u.role
FROM users u
JOIN tenant_owners t_o ON u.id = t_o.user_id
WHERE t_o.tenant_id = $1
`

type ListTenantOwnersRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Role  string    `json:"role"`
}

func (q *Queries) ListTenantOwners(ctx context.Context, tenantID uuid.UUID) ([]ListTenantOwnersRow, error) {
	rows, err := q.query(ctx, q.listTenantOwnersStmt, listTenantOwners, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantOwnersRow
	for rows.Next() {
		var i ListTenantOwnersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, created_at, icon_url, cover_url, description, owner_id, category FROM tenants 
WHERE (name ILIKE '%' || $1 || '%' OR COALESCE(category, '') ILIKE '%' || $1 || '%')
AND (COALESCE(category, '') = $2 OR $2 = '')
ORDER BY name
`

type ListTenantsParams struct {
	Column1  sql.NullString `json:"column_1"`
	Category sql.NullString `json:"category"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.query(ctx, q.listTenantsStmt, listTenants, arg.Column1, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.IconUrl,
			&i.CoverUrl,
			&i.Description,
			&i.OwnerID,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.LoyaltyTier,
			&i.FullName,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantOwner = `-- name: RemoveTenantOwner :exec
DELETE FROM tenant_owners WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantOwnerParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTenantOwner(ctx context.Context, arg RemoveTenantOwnerParams) error {
	_, err := q.exec(ctx, q.removeTenantOwnerStmt, removeTenantOwner, arg.TenantID, arg.UserID)
	return err
}

const setTenantOwner = `-- name: SetTenantOwner :one
UPDATE tenants SET owner_id = $2 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id, category
`

type SetTenantOwnerParams struct {
	ID      uuid.UUID     `json:"id"`
	OwnerID uuid.NullUUID `json:"owner_id"`
}

func (q *Queries) SetTenantOwner(ctx context.Context, arg SetTenantOwnerParams) (Tenant, error) {
	row := q.queryRow(ctx, q.setTenantOwnerStmt, setTenantOwner, arg.ID, arg.OwnerID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
		&i.Category,
	)
	return i, err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
SET title = $2, content_md = $3
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, title, content_md, published_at
`

type UpdateBlogParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	ContentMd string    `json:"content_md"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.updateBlogStmt, updateBlog,
		arg.ID,
		arg.Title,
		arg.ContentMd,
		arg.TenantID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.ContentMd,
		&i.PublishedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = $2 WHERE id = $1 AND tenant_id = $3 RETURNING id, tenant_id, user_id, status, total_amount, created_at
`

type UpdateOrderStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.queryRow(ctx, q.updateOrderStatusStmt, updateOrderStatus, arg.ID, arg.Status, arg.TenantID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products 
SET name = $2, description = $3, price = $4, stock = $5, image_url = $6, category = $7
WHERE id = $1 AND tenant_id = $8
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at, category
`

type UpdateProductParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Price       string         `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    sql.NullString `json:"image_url"`
	Category    sql.NullString `json:"category"`
	TenantID    uuid.UUID      `json:"tenant_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStmt, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.Category,
		arg.TenantID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products SET stock = stock - $2
WHERE id = $1 AND tenant_id = $3 AND stock >= $2
RETURNING id, tenant_id, name, description, price, stock, image_url, created_at, category
`

type UpdateProductStockParams struct {
	ID       uuid.UUID `json:"id"`
	Stock    int32     `json:"stock"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.queryRow(ctx, q.updateProductStockStmt, updateProductStock, arg.ID, arg.Stock, arg.TenantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, slug = $3 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id, category
`

type UpdateTenantParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.queryRow(ctx, q.updateTenantStmt, updateTenant, arg.ID, arg.Name, arg.Slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
		&i.Category,
	)
	return i, err
}

const updateTenantAppearance = `-- name: UpdateTenantAppearance :one
UPDATE tenants SET cover_url = $2, description = $3 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id, category
`

type UpdateTenantAppearanceParams struct {
	ID          uuid.UUID      `json:"id"`
	CoverUrl    sql.NullString `json:"cover_url"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpdateTenantAppearance(ctx context.Context, arg UpdateTenantAppearanceParams) (Tenant, error) {
	row := q.queryRow(ctx, q.updateTenantAppearanceStmt, updateTenantAppearance, arg.ID, arg.CoverUrl, arg.Description)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
		&i.Category,
	)
	return i, err
}

const updateTenantIcon = `-- name: UpdateTenantIcon :one
UPDATE tenants SET icon_url = $2 WHERE id = $1 RETURNING id, name, slug, created_at, icon_url, cover_url, description, owner_id, category
`

type UpdateTenantIconParams struct {
	ID      uuid.UUID      `json:"id"`
	IconUrl sql.NullString `json:"icon_url"`
}

func (q *Queries) UpdateTenantIcon(ctx context.Context, arg UpdateTenantIconParams) (Tenant, error) {
	row := q.queryRow(ctx, q.updateTenantIconStmt, updateTenantIcon, arg.ID, arg.IconUrl)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.IconUrl,
		&i.CoverUrl,
		&i.Description,
		&i.OwnerID,
		&i.Category,
	)
	return i, err
}

const updateUserLoyaltyTier = `-- name: UpdateUserLoyaltyTier :one
UPDATE users SET loyalty_tier = $2 WHERE id = $1 RETURNING id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city
`

type UpdateUserLoyaltyTierParams struct {
	ID          uuid.UUID      `json:"id"`
	LoyaltyTier sql.NullString `json:"loyalty_tier"`
}

func (q *Queries) UpdateUserLoyaltyTier(ctx context.Context, arg UpdateUserLoyaltyTierParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserLoyaltyTierStmt, updateUserLoyaltyTier, arg.ID, arg.LoyaltyTier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.LoyaltyTier,
		&i.FullName,
		&i.Street,
		&i.ZipCode,
		&i.City,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1 RETURNING id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserRoleStmt, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.LoyaltyTier,
		&i.FullName,
		&i.Street,
		&i.ZipCode,
		&i.City,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET full_name = $2, street = $3, zip_code = $4, city = $5 WHERE id = $1 RETURNING id, tenant_id, email, password_hash, role, created_at, loyalty_tier, full_name, street, zip_code, city
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID      `json:"id"`
	FullName sql.NullString `json:"full_name"`
	Street   sql.NullString `json:"street"`
	ZipCode  sql.NullString `json:"zip_code"`
	City     sql.NullString `json:"city"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserProfileStmt, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Street,
		arg.ZipCode,
		arg.City,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.LoyaltyTier,
		&i.FullName,
		&i.Street,
		&i.ZipCode,
		&i.City,
	)
	return i, err
}
