// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID         int32
	Title      string
	Content    string
	UserID     int32
	Path       string
	ModifiedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
}

type Order struct {
	ID          int32
	Address     string
	UserID      int32
	IsCompleted pgtype.Bool
	CreatedAt   pgtype.Timestamp
}

type OrderProduct struct {
	ID        int32
	OrderID   int32
	ProductID int32
	Quantity  int32
	CreatedAt pgtype.Timestamp
}

type Product struct {
	ID          int32
	Name        string
	Price       pgtype.Numeric
	ImageUrl    string
	IsAvailable pgtype.Bool
	CreatedAt   pgtype.Timestamp
}

type User struct {
	ID        int32
	Name      string
	Password  string
	Email     string
	IsAdmin   pgtype.Bool
	CreatedAt pgtype.Timestamp
}
